version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres-container
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=account
    ports:
      - '5555:5432'
    volumes:
      - C:\Users\dogan\Desktop\dbaccount:/var/lib/postgresql/data
volumes:
  db:
    driver: local